---
version: '3.7'

networks:
  default:
    name: ingress_net
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "10.80.0.0/16"

services:
  traefik:
    image: traefik:v2.4
    hostname: ingress-traefik
    ports:
      - target: 80
        published: 80
        #mode: host
      - target: 443
        published: 443
        #mode: host
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/ping"]
      interval: 10s
      timeout: 5s
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        order: start-first
      labels:
        - "traefik.enable=false"
