---
version: '3.7'

networks:
  ingress-net:
    name: ingress_net
    driver: overlay
    attachable: true

services:
  traefik:
    image: traefik:v2.2
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - "8080:8080"
    networks:
      - ingress-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
      - ./traefik/traefik.conf.d:/etc/traefik/traefik.conf.d
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/ping"]
      interval: 10s
      timeout: 5s
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=false