---
api:
  insecure: true
  dashboard: true

log:
  level: INFO

ping: {}

accessLog: {}

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    watch: true
  file:
    directory: "/etc/traefik/traefik.conf.d/"
    watch: true

certificatesResolvers:
  myResolver:
    acme:
      email: "your_email_here@example.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
  myResolver-tls:
    acme:
      email: "your_email_here@example.com"
      storage: "/etc/traefik/acme.json"
      tlsChallenge: true
